// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://updikdnvycgkgfhtgyqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwZGlrZG52eWNna2dmaHRneXFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTY0MDAsImV4cCI6MjA2ODg3MjQwMH0._63fHPExMcZK4XvPJD2w4lr_RgPJDzcPVWa-b3hGt_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});